package com.adsale.HEATEC.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "COUNTRY".
 */
public class Country {

    private String CountryID;
    private String CountryNameTW;
    private String CountryNameCN;
    private String CountryNameEN;
    private String SortTW;
    private String SortCN;
    private String SortEN;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Country() {
    }

    public Country(String CountryID, String CountryNameTW, String CountryNameCN, String CountryNameEN, String SortTW, String SortCN, String SortEN) {
        this.CountryID = CountryID;
        this.CountryNameTW = CountryNameTW;
        this.CountryNameCN = CountryNameCN;
        this.CountryNameEN = CountryNameEN;
        this.SortTW = SortTW;
        this.SortCN = SortCN;
        this.SortEN = SortEN;
    }

    public String getCountryID() {
        return CountryID;
    }

    public void setCountryID(String CountryID) {
        this.CountryID = CountryID;
    }

    public String getCountryNameTW() {
        return CountryNameTW;
    }

    public void setCountryNameTW(String CountryNameTW) {
        this.CountryNameTW = CountryNameTW;
    }

    public String getCountryNameCN() {
        return CountryNameCN;
    }

    public void setCountryNameCN(String CountryNameCN) {
        this.CountryNameCN = CountryNameCN;
    }

    public String getCountryNameEN() {
        return CountryNameEN;
    }

    public void setCountryNameEN(String CountryNameEN) {
        this.CountryNameEN = CountryNameEN;
    }

    public String getSortTW() {
        return SortTW;
    }

    public void setSortTW(String SortTW) {
        this.SortTW = SortTW;
    }

    public String getSortCN() {
        return SortCN;
    }

    public void setSortCN(String SortCN) {
        this.SortCN = SortCN;
    }

    public String getSortEN() {
        return SortEN;
    }

    public void setSortEN(String SortEN) {
        this.SortEN = SortEN;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
