package com.adsale.HEATEC.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.adsale.HEATEC.dao.Country;
import com.adsale.HEATEC.dao.Exhibitor;
import com.adsale.HEATEC.dao.ExhibitorIndustryDtl;
import com.adsale.HEATEC.dao.Floor;
import com.adsale.HEATEC.dao.Industry;
import com.adsale.HEATEC.dao.MainIcon;
import com.adsale.HEATEC.dao.MapFloor;
import com.adsale.HEATEC.dao.News;
import com.adsale.HEATEC.dao.NewsLink;
import com.adsale.HEATEC.dao.ScheduleInfo;
import com.adsale.HEATEC.dao.UpdateDate;
import com.adsale.HEATEC.dao.WebContent;

import com.adsale.HEATEC.dao.CountryDao;
import com.adsale.HEATEC.dao.ExhibitorDao;
import com.adsale.HEATEC.dao.ExhibitorIndustryDtlDao;
import com.adsale.HEATEC.dao.FloorDao;
import com.adsale.HEATEC.dao.IndustryDao;
import com.adsale.HEATEC.dao.MainIconDao;
import com.adsale.HEATEC.dao.MapFloorDao;
import com.adsale.HEATEC.dao.NewsDao;
import com.adsale.HEATEC.dao.NewsLinkDao;
import com.adsale.HEATEC.dao.ScheduleInfoDao;
import com.adsale.HEATEC.dao.UpdateDateDao;
import com.adsale.HEATEC.dao.WebContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig countryDaoConfig;
    private final DaoConfig exhibitorDaoConfig;
    private final DaoConfig exhibitorIndustryDtlDaoConfig;
    private final DaoConfig floorDaoConfig;
    private final DaoConfig industryDaoConfig;
    private final DaoConfig mainIconDaoConfig;
    private final DaoConfig mapFloorDaoConfig;
    private final DaoConfig newsDaoConfig;
    private final DaoConfig newsLinkDaoConfig;
    private final DaoConfig scheduleInfoDaoConfig;
    private final DaoConfig updateDateDaoConfig;
    private final DaoConfig webContentDaoConfig;

    private final CountryDao countryDao;
    private final ExhibitorDao exhibitorDao;
    private final ExhibitorIndustryDtlDao exhibitorIndustryDtlDao;
    private final FloorDao floorDao;
    private final IndustryDao industryDao;
    private final MainIconDao mainIconDao;
    private final MapFloorDao mapFloorDao;
    private final NewsDao newsDao;
    private final NewsLinkDao newsLinkDao;
    private final ScheduleInfoDao scheduleInfoDao;
    private final UpdateDateDao updateDateDao;
    private final WebContentDao webContentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        exhibitorDaoConfig = daoConfigMap.get(ExhibitorDao.class).clone();
        exhibitorDaoConfig.initIdentityScope(type);

        exhibitorIndustryDtlDaoConfig = daoConfigMap.get(ExhibitorIndustryDtlDao.class).clone();
        exhibitorIndustryDtlDaoConfig.initIdentityScope(type);

        floorDaoConfig = daoConfigMap.get(FloorDao.class).clone();
        floorDaoConfig.initIdentityScope(type);

        industryDaoConfig = daoConfigMap.get(IndustryDao.class).clone();
        industryDaoConfig.initIdentityScope(type);

        mainIconDaoConfig = daoConfigMap.get(MainIconDao.class).clone();
        mainIconDaoConfig.initIdentityScope(type);

        mapFloorDaoConfig = daoConfigMap.get(MapFloorDao.class).clone();
        mapFloorDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        newsLinkDaoConfig = daoConfigMap.get(NewsLinkDao.class).clone();
        newsLinkDaoConfig.initIdentityScope(type);

        scheduleInfoDaoConfig = daoConfigMap.get(ScheduleInfoDao.class).clone();
        scheduleInfoDaoConfig.initIdentityScope(type);

        updateDateDaoConfig = daoConfigMap.get(UpdateDateDao.class).clone();
        updateDateDaoConfig.initIdentityScope(type);

        webContentDaoConfig = daoConfigMap.get(WebContentDao.class).clone();
        webContentDaoConfig.initIdentityScope(type);

        countryDao = new CountryDao(countryDaoConfig, this);
        exhibitorDao = new ExhibitorDao(exhibitorDaoConfig, this);
        exhibitorIndustryDtlDao = new ExhibitorIndustryDtlDao(exhibitorIndustryDtlDaoConfig, this);
        floorDao = new FloorDao(floorDaoConfig, this);
        industryDao = new IndustryDao(industryDaoConfig, this);
        mainIconDao = new MainIconDao(mainIconDaoConfig, this);
        mapFloorDao = new MapFloorDao(mapFloorDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);
        newsLinkDao = new NewsLinkDao(newsLinkDaoConfig, this);
        scheduleInfoDao = new ScheduleInfoDao(scheduleInfoDaoConfig, this);
        updateDateDao = new UpdateDateDao(updateDateDaoConfig, this);
        webContentDao = new WebContentDao(webContentDaoConfig, this);

        registerDao(Country.class, countryDao);
        registerDao(Exhibitor.class, exhibitorDao);
        registerDao(ExhibitorIndustryDtl.class, exhibitorIndustryDtlDao);
        registerDao(Floor.class, floorDao);
        registerDao(Industry.class, industryDao);
        registerDao(MainIcon.class, mainIconDao);
        registerDao(MapFloor.class, mapFloorDao);
        registerDao(News.class, newsDao);
        registerDao(NewsLink.class, newsLinkDao);
        registerDao(ScheduleInfo.class, scheduleInfoDao);
        registerDao(UpdateDate.class, updateDateDao);
        registerDao(WebContent.class, webContentDao);
    }
    
    public void clear() {
        countryDaoConfig.getIdentityScope().clear();
        exhibitorDaoConfig.getIdentityScope().clear();
        exhibitorIndustryDtlDaoConfig.getIdentityScope().clear();
        floorDaoConfig.getIdentityScope().clear();
        industryDaoConfig.getIdentityScope().clear();
        mainIconDaoConfig.getIdentityScope().clear();
        mapFloorDaoConfig.getIdentityScope().clear();
        newsDaoConfig.getIdentityScope().clear();
        newsLinkDaoConfig.getIdentityScope().clear();
        scheduleInfoDaoConfig.getIdentityScope().clear();
        updateDateDaoConfig.getIdentityScope().clear();
        webContentDaoConfig.getIdentityScope().clear();
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public ExhibitorDao getExhibitorDao() {
        return exhibitorDao;
    }

    public ExhibitorIndustryDtlDao getExhibitorIndustryDtlDao() {
        return exhibitorIndustryDtlDao;
    }

    public FloorDao getFloorDao() {
        return floorDao;
    }

    public IndustryDao getIndustryDao() {
        return industryDao;
    }

    public MainIconDao getMainIconDao() {
        return mainIconDao;
    }

    public MapFloorDao getMapFloorDao() {
        return mapFloorDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public NewsLinkDao getNewsLinkDao() {
        return newsLinkDao;
    }

    public ScheduleInfoDao getScheduleInfoDao() {
        return scheduleInfoDao;
    }

    public UpdateDateDao getUpdateDateDao() {
        return updateDateDao;
    }

    public WebContentDao getWebContentDao() {
        return webContentDao;
    }

}
