package com.adsale.HEATEC.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EXHIBITOR_INDUSTRY_DTL".
 */
public class ExhibitorIndustryDtl {

    private String CompanyID;
    private Boolean IsDelete;
    /** Not-null value. */
    private String IndustryID;
    /** Not-null value. */
    private String CreateDateTime;
    /** Not-null value. */
    private String UpdateDateTime;
    /** Not-null value. */
    private String RecordTimeStamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ExhibitorIndustryDtl() {
    }

    public ExhibitorIndustryDtl(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public ExhibitorIndustryDtl(String CompanyID, Boolean IsDelete, String IndustryID, String CreateDateTime, String UpdateDateTime, String RecordTimeStamp) {
        this.CompanyID = CompanyID;
        this.IsDelete = IsDelete;
        this.IndustryID = IndustryID;
        this.CreateDateTime = CreateDateTime;
        this.UpdateDateTime = UpdateDateTime;
        this.RecordTimeStamp = RecordTimeStamp;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public Boolean getIsDelete() {
        return IsDelete;
    }

    public void setIsDelete(Boolean IsDelete) {
        this.IsDelete = IsDelete;
    }

    /** Not-null value. */
    public String getIndustryID() {
        return IndustryID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIndustryID(String IndustryID) {
        this.IndustryID = IndustryID;
    }

    /** Not-null value. */
    public String getCreateDateTime() {
        return CreateDateTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateDateTime(String CreateDateTime) {
        this.CreateDateTime = CreateDateTime;
    }

    /** Not-null value. */
    public String getUpdateDateTime() {
        return UpdateDateTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdateDateTime(String UpdateDateTime) {
        this.UpdateDateTime = UpdateDateTime;
    }

    /** Not-null value. */
    public String getRecordTimeStamp() {
        return RecordTimeStamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecordTimeStamp(String RecordTimeStamp) {
        this.RecordTimeStamp = RecordTimeStamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
