package com.adsale.HEATEC.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SCHEDULE_INFO".
 */
public class ScheduleInfo {

    private Long ScheduleID;
    private String Title;
    private String Note;
    private String Location;
    private String CompanyID;
    private String StartTime;
    private Integer Length;
    private Integer Allday;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ScheduleInfo() {
    }

    public ScheduleInfo(Long ScheduleID) {
        this.ScheduleID = ScheduleID;
    }

    public ScheduleInfo(Long ScheduleID, String Title, String Note, String Location, String CompanyID, String StartTime, Integer Length, Integer Allday) {
        this.ScheduleID = ScheduleID;
        this.Title = Title;
        this.Note = Note;
        this.Location = Location;
        this.CompanyID = CompanyID;
        this.StartTime = StartTime;
        this.Length = Length;
        this.Allday = Allday;
    }

    public Long getScheduleID() {
        return ScheduleID;
    }

    public void setScheduleID(Long ScheduleID) {
        this.ScheduleID = ScheduleID;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getNote() {
        return Note;
    }

    public void setNote(String Note) {
        this.Note = Note;
    }

    public String getLocation() {
        return Location;
    }

    public void setLocation(String Location) {
        this.Location = Location;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getStartTime() {
        return StartTime;
    }

    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    public Integer getLength() {
        return Length;
    }

    public void setLength(Integer Length) {
        this.Length = Length;
    }

    public Integer getAllday() {
        return Allday;
    }

    public void setAllday(Integer Allday) {
        this.Allday = Allday;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
