package com.adsale.HEATEC.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.adsale.HEATEC.util.Constant;
import com.adsale.HEATEC.util.LogUtil;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import static com.adsale.HEATEC.util.Constant.SCHEDULE_MONTH;

/**
 * Entity mapped to table "SCHEDULE_INFO".
 */
public class ScheduleInfo implements Parcelable {


    private Long ScheduleID;
    private String CompanyID;
    private String Title;
    private String Location;
    private Integer DayIndex;
    private String StartTime;
    private Integer Hour;
    private Integer Minute;
    private String Note;

    // KEEP FIELDS - put your custom fields here
    private String StartDateTime;
    public Integer position;
    // KEEP FIELDS END

    public ScheduleInfo() {
    }

    public ScheduleInfo(Long ScheduleID) {
        this.ScheduleID = ScheduleID;
    }

    public ScheduleInfo(Long ScheduleID, String CompanyID, String Title, String Location, Integer DayIndex, String StartTime, Integer Hour, Integer Minute, String Note) {
        this.ScheduleID = ScheduleID;
        this.CompanyID = CompanyID;
        this.Title = Title;
        this.Location = Location;
        this.DayIndex = DayIndex;
        this.StartTime = StartTime;
        this.Hour = Hour;
        this.Minute = Minute;
        this.Note = Note;
    }

    public Long getScheduleID() {
        return ScheduleID;
    }

    public void setScheduleID(Long ScheduleID) {
        this.ScheduleID = ScheduleID;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getLocation() {
        return Location;
    }

    public void setLocation(String Location) {
        this.Location = Location;
    }

    public Integer getDayIndex() {
        return DayIndex;
    }

    public void setDayIndex(Integer DayIndex) {
        this.DayIndex = DayIndex;
    }

    public String getStartTime() {
        return StartTime;
    }

    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    public Integer getHour() {
        return Hour;
    }

    public void setHour(Integer Hour) {
        this.Hour = Hour;
    }

    public Integer getMinute() {
        return Minute;
    }

    public void setMinute(Integer Minute) {
        this.Minute = Minute;
    }

    public String getNote() {
        return Note;
    }

    public void setNote(String Note) {
        this.Note = Note;
    }

    // KEEP METHODS - put your custom methods here
    public ScheduleInfo(String CompanyID, String Title, String Location, Integer DayIndex, String StartTime, Integer Hour, Integer Minute, String Note) {
        this.CompanyID = CompanyID;
        this.Title = Title;
        this.Location = Location;
        this.DayIndex = DayIndex;
        this.StartTime = StartTime;
        this.Hour = Hour;
        this.Minute = Minute;
        this.Note = Note;
    }

    @Override
    public String toString() {
        return "ScheduleInfo{" +
                "ScheduleID=" + ScheduleID +
                ", CompanyID='" + CompanyID + '\'' +
                ", Title='" + Title + '\'' +
                ", Location='" + Location + '\'' +
                ", DayIndex=" + DayIndex +
                ", StartTime='" + StartTime + '\'' +
                ", Hour=" + Hour +
                ", Minute=" + Minute +
                ", Note='" + Note + '\'' +
                '}';
    }

    public String getStartDateTime(int dateIndex, String startTime) {
        String time;
        if (dateIndex == 0) {
            time = Constant.SCHEDULE_MONTH.concat("-").concat(Constant.SCHEDULE_DAY0).concat(" ").concat(startTime);
        } else if (dateIndex == 1) {
            time = SCHEDULE_MONTH.concat("-").concat(Constant.SCHEDULE_DAY1).concat(" ").concat(startTime);
        } else {
            time = SCHEDULE_MONTH.concat("-").concat(Constant.SCHEDULE_DAY_END).concat(" ").concat(startTime);
        }
        //// TODO: 2017/10/13 直接把这部分在save时加入数据库， starttime = 09:00 AM 
        LogUtil.i("getStartDateTime", "TIME=" + time);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm a", Locale.getDefault());
        try {
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault());
            Date date=sdf1.parse(time);
            time = sdf.format(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        LogUtil.i("getStartDateTime", "time==" + time);
        return time;
    }
    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.ScheduleID);
        dest.writeString(this.CompanyID);
        dest.writeString(this.Title);
        dest.writeString(this.Location);
        dest.writeValue(this.DayIndex);
        dest.writeString(this.StartTime);
        dest.writeValue(this.Hour);
        dest.writeValue(this.Minute);
        dest.writeString(this.Note);
    }

    protected ScheduleInfo(Parcel in) {
        this.ScheduleID = (Long) in.readValue(Long.class.getClassLoader());
        this.CompanyID = in.readString();
        this.Title = in.readString();
        this.Location = in.readString();
        this.DayIndex = (Integer) in.readValue(Integer.class.getClassLoader());
        this.StartTime = in.readString();
        this.Hour = (Integer) in.readValue(Integer.class.getClassLoader());
        this.Minute = (Integer) in.readValue(Integer.class.getClassLoader());
        this.Note = in.readString();
    }

    public static final Parcelable.Creator<ScheduleInfo> CREATOR = new Parcelable.Creator<ScheduleInfo>() {
        public ScheduleInfo createFromParcel(Parcel source) {
            return new ScheduleInfo(source);
        }

        public ScheduleInfo[] newArray(int size) {
            return new ScheduleInfo[size];
        }
    };
}
