package com.adsale.HEATEC.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.adsale.HEATEC.util.SystemMethod;

/**
 * Entity mapped to table "WEB_CONTENT".
 */
public class WebContent {

    private String PageId;
    private Boolean IsDelete;
    private String TitleTW;
    private String TitleCN;
    private String TitleEN;
    private Integer CType;
    private String CFile;
    private String ZipDateTime;
    private String ContentEN;
    private String ContentSC;
    private String ContentTC;
    private String CreateDateTime;
    private String UpdateDateTime;
    private String RecordTimeStamp;
    private Integer IsDown;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public WebContent() {
    }

    public WebContent(String PageId) {
        this.PageId = PageId;
    }

    public WebContent(String PageId, Boolean IsDelete, String TitleTW, String TitleCN, String TitleEN, Integer CType, String CFile, String ZipDateTime, String ContentEN, String ContentSC, String ContentTC, String CreateDateTime, String UpdateDateTime, String RecordTimeStamp, Integer IsDown) {
        this.PageId = PageId;
        this.IsDelete = IsDelete;
        this.TitleTW = TitleTW;
        this.TitleCN = TitleCN;
        this.TitleEN = TitleEN;
        this.CType = CType;
        this.CFile = CFile;
        this.ZipDateTime = ZipDateTime;
        this.ContentEN = ContentEN;
        this.ContentSC = ContentSC;
        this.ContentTC = ContentTC;
        this.CreateDateTime = CreateDateTime;
        this.UpdateDateTime = UpdateDateTime;
        this.RecordTimeStamp = RecordTimeStamp;
        this.IsDown = IsDown;
    }

    public String getPageId() {
        return PageId;
    }

    public void setPageId(String PageId) {
        this.PageId = PageId;
    }

    public Boolean getIsDelete() {
        return IsDelete;
    }

    public void setIsDelete(Boolean IsDelete) {
        this.IsDelete = IsDelete;
    }

    public String getTitleTW() {
        return TitleTW;
    }

    public void setTitleTW(String TitleTW) {
        this.TitleTW = TitleTW;
    }

    public String getTitleCN() {
        return TitleCN;
    }

    public void setTitleCN(String TitleCN) {
        this.TitleCN = TitleCN;
    }

    public String getTitleEN() {
        return TitleEN;
    }

    public void setTitleEN(String TitleEN) {
        this.TitleEN = TitleEN;
    }

    public Integer getCType() {
        return CType;
    }

    public void setCType(Integer CType) {
        this.CType = CType;
    }

    public String getCFile() {
        return CFile;
    }

    public void setCFile(String CFile) {
        this.CFile = CFile;
    }

    public String getZipDateTime() {
        return ZipDateTime;
    }

    public void setZipDateTime(String ZipDateTime) {
        this.ZipDateTime = ZipDateTime;
    }

    public String getContentEN() {
        return ContentEN;
    }

    public void setContentEN(String ContentEN) {
        this.ContentEN = ContentEN;
    }

    public String getContentSC() {
        return ContentSC;
    }

    public void setContentSC(String ContentSC) {
        this.ContentSC = ContentSC;
    }

    public String getContentTC() {
        return ContentTC;
    }

    public void setContentTC(String ContentTC) {
        this.ContentTC = ContentTC;
    }

    public String getCreateDateTime() {
        return CreateDateTime;
    }

    public void setCreateDateTime(String CreateDateTime) {
        this.CreateDateTime = CreateDateTime;
    }

    public String getUpdateDateTime() {
        return UpdateDateTime;
    }

    public void setUpdateDateTime(String UpdateDateTime) {
        this.UpdateDateTime = UpdateDateTime;
    }

    public String getRecordTimeStamp() {
        return RecordTimeStamp;
    }

    public void setRecordTimeStamp(String RecordTimeStamp) {
        this.RecordTimeStamp = RecordTimeStamp;
    }

    public Integer getIsDown() {
        return IsDown;
    }

    public void setIsDown(Integer IsDown) {
        this.IsDown = IsDown;
    }

    // KEEP METHODS - put your custom methods here

    public String getTitle(int language){
        return SystemMethod.getName(language,TitleTW,TitleEN,TitleCN);
    }
    // KEEP METHODS END

}
